#!/bin/bash
sudo -u postgres \
/usr/local/pgsql/bin/psql -c 'DROP DATABASE IF EXISTS pi;' && \
/usr/local/pgsql/bin/psql -c 'CREATE DATABASE pi OWNER benh;' && \
/usr/local/pgsql/bin/psql -c 'GRANT ALL ON DATABASE pi TO benh;'
